baseurl = "https://michaeldavie.github.io"
title = "Michael Davie's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Michael Davie Blog"

  image_404 = "img/404-bg.jpg"
  title_404 = "Page not found :("
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Dad, security engineer, home automation nerd"
  sidebar_avatar = "img/avatar.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false 
  featured_condition_size = 1 
  
  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = false
  linkedin       = "https://www.linkedin.com/in/michael-davie-peng"
  github         = "https://github.com/michaeldavie"
  keybase       = "https://keybase.io/michaeldavie"
    
[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"